# Prevent messages for libraries of rubocop
AllCops:
  NewCops: enable
  SuggestExtensions: false

# Disabling ABC size for now as refactoring few places seems pointless for now
Metrics/AbcSize:
  Enabled: false

# Disabling this becuase we are using `set` and `get` prefixed methods to keep some commonality across SDKs
Naming/AccessorMethodName:
  Enabled: false

# Disabling this until we figure out a better way than using openstruct
# Currently we use open struct because this gives us an object representing the JSON 
# with accessor style methods.
Style/OpenStructUse:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'

# Just ignoring test helper for headless auth.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/smartcar/helpers/auth_helper.rb'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10
